name: Automation Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - api
        - web

jobs:
  api-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'api' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run API Tests
        run: ./gradlew apiTest
      - name: List Cucumber Reports Directory
        run: ls -l build/reports/cucumber/api/
      - name: Check for API JSON Report
        run: |
          if [ ! -f build/reports/cucumber/api/cucumber-api-report.json ]; then
            echo "Cucumber JSON report not found!"
            exit 1
          fi
      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            build/reports/cucumber/api/
            build/test-results/
          retention-days: 30

  web-tests:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'web' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Web Tests
        run: ./gradlew webTest
      - name: List Cucumber Reports Directory
        run: ls -l build/reports/cucumber/web/
      - name: Check for Web JSON Report
        run: |
          if [ ! -f build/reports/cucumber/web/cucumber-web-report.json ]; then
            echo "Cucumber JSON report not found!"
            exit 1
          fi
      - name: Upload Web Test Results
        uses: actions/upload-artifact@v4
        with:
          name: web-test-results
          path: |
            build/reports/cucumber/web/
            build/test-results/
          retention-days: 30
      - name: Upload Web Test Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: web-test-screenshots
          path: |
            build/screenshots/
          retention-days: 7

  full-test-suite:
    runs-on: ubuntu-latest
    needs: [api-tests, web-tests]
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.test_type == 'all' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run All Tests
        run: ./gradlew allTests
      - name: List Cucumber Reports Directory
        run: ls -l build/reports/cucumber/all/
      - name: Check for Combined JSON Report
        run: |
          if [ ! -f build/reports/cucumber/all/cucumber-all-report.json ]; then
            echo "Cucumber JSON report not found!"
            exit 1
          fi
      - name: Upload Combined Test Results
        uses: actions/upload-artifact@v4
        with:
          name: combined-test-results
          path: |
            build/reports/cucumber/
            build/test-results/
          retention-days: 30
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: 'build/test-results/**/*.xml'
          reporter: java-junit
      - name: Test Summary
        run: |
          echo "## Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "### API Tests" >> $GITHUB_STEP_SUMMARY
          echo "- API test results are available in the artifacts" >> $GITHUB_STEP_SUMMARY
          echo "### Web Tests" >> $GITHUB_STEP_SUMMARY
          echo "- Web test results are available in the artifacts" >> $GITHUB_STEP_SUMMARY
          echo "### Combined Results" >> $GITHUB_STEP_SUMMARY
          echo "- Combined test reports are available in the artifacts" >> $GITHUB_STEP_SUMMARY